### ISSUE TITLE
Live Citation is broken

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#168]
This is on 0.3.1
See on the demo server:
http://demo.librecat.org/livecitation?style=mla&id=20

The citation stuff now also shows two errors:
```
citeproc_1       | ERR! CslLoader.resolveStyle styleName not specified
citeproc_1       | ERR! Error while handling request:  Error: shortName not specified
citeproc_1       | ERR! Error while handling request:      at /src/lib/styles.js:172:20
citeproc_1       | ERR! Error while handling request:      at tryCatch2 (/src/node_modules/bluebird/js/main/util.js:74:19)
citeproc_1       | ERR! Error while handling request:      at Promise$_resolveFromResolver [as _resolveFromResolver] (/src/node_modules/bluebird/js/main/promise.js:606:13)
citeproc_1       | ERR! Error while handling request:      at new Promise (/src/node_modules/bluebird/js/main/promise.js:88:37)
citeproc_1       | ERR! Error while handling request:      at exports.CslLoader.resolveStyle (/src/lib/styles.js:169:12)
citeproc_1       | ERR! Error while handling request:      at Promise.resolve.then.then.then.responseJson (/src/lib/citeServer.js:239:41)
citeproc_1       | ERR! Error while handling request:      at tryCatch1 (/src/node_modules/bluebird/js/main/util.js:64:19)
citeproc_1       | ERR! Error while handling request:      at Promise$_callHandler [as _callHandler] (/src/node_modules/bluebird/js/main/promise.js:706:13)
citeproc_1       | ERR! Error while handling request:      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/src/node_modules/bluebird/js/main/promise.js:722:18)
citeproc_1       | ERR! Error while handling request:      at Promise$_settlePromiseAt [as _settlePromiseAt] (/src/node_modules/bluebird/js/main/promise.js:892:14)
citeproc_1       | ERR! Error while handling request:      at Promise$_fulfillPromises [as _fulfillPromises] (/src/node_modules/bluebird/js/main/promise.js:1037:14)
citeproc_1       | ERR! Error while handling request:   [Error: shortName not specified]
librecat_1       | Wide character in print at /srv/LibreCat/local/lib/perl5/Log/Log4perl/Appender/File.pm line 276, <GEN0> line 628.
```
Note that the last line is from LibreCat itself, the rest from Citeproc.

**Comment by vpeil** [comment]
I am currently working on this...
