### ISSUE TITLE
Support for Ubuntu

### ISSUE THREAD

**Issue by lightonphiri** [LibreCat/LibreCat#687]
We would really want to experiment with LibreCat, however, we have had a number of challenges setting it up on Ubuntu. There seems to be a closed issue on this: issue #344, however, the link to the Debian Wiki page is incomplete. 
Is there anyone who has successfully installed LibreCat on Ubuntu and able to share their experiences/workarounds?

**Comment by phochste** [comment]
LibreCat has is supported on Ubuntu by the way. We run all our test environments on Travis.org (integration service), these test run on Ubuntu 14. See https://github.com/LibreCat/LibreCat/blob/master/.travis.yml for install hints

**Comment by vpeil** [comment]
I am running a debian box for development without issues. @lightonphiri what exactly does not work?

**Comment by lightonphiri** [comment]
We managed to set up and configure a LibreCat instance on Ubuntu 16.04. We have been able to login using the default einstein account and, additionally, managed to create sample user accounts. However, we are experiencing two issues:
1. Attempting to upload sample publications results in the error below. While this appears to be a generic mariadb error, we figured people here would be able to help.
`{
   "exception" : "DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at /home/lightonphiri/projects/work/2019/LibreCat/local/lib/perl5/Catmandu/Store/DBI/Handler/MySQL.pm line 93.\n",
   "error" : "DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at /home/lightonphiri/projects/work/2019/LibreCat/local/lib/perl5/Catmandu/Store/DBI/Handler/MySQL.pm line 93.\n"
}`

2. We have noticed the following elasticsearch errors as we browse through the instance. Any ideas on what could be causing these errors. We are guessing this might, in part, be the reason why we are unable to upload publications.
```
[2019-02-08 22:25:01,334][DEBUG][action.search.type       ] [Hogun] [publication][1], node[Vj2MnZUSR-iN-rZQYrfLTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2749bf4b] lastShard [true]
org.elasticsearch.search.SearchParseException: [publication][1]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][1]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
[2019-02-08 22:25:01,337][DEBUG][action.search.type       ] [Hogun] [publication][0], node[Vj2MnZUSR-iN-rZQYrfLTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2749bf4b] lastShard [true]
org.elasticsearch.search.SearchParseException: [publication][0]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][0]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
[2019-02-08 22:25:01,347][DEBUG][action.search.type       ] [Hogun] [publication][3], node[Vj2MnZUSR-iN-rZQYrfLTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2749bf4b] lastShard [true]
org.elasticsearch.search.SearchParseException: [publication][3]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][3]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
[2019-02-08 22:25:01,343][DEBUG][action.search.type       ] [Hogun] [publication][2], node[Vj2MnZUSR-iN-rZQYrfLTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2749bf4b] lastShard [true]
org.elasticsearch.search.SearchParseException: [publication][2]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][2]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
[2019-02-08 22:25:01,358][DEBUG][action.search.type       ] [Hogun] [publication][4], node[Vj2MnZUSR-iN-rZQYrfLTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2749bf4b]
org.elasticsearch.search.SearchParseException: [publication][4]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][4]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
[2019-02-08 22:25:01,361][DEBUG][action.search.type       ] [Hogun] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [publication][4]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [Failed to parse source [{"query":{"bool":{"must_not":[{"match_phrase":{"status":{"query":"deleted"}}}]}},"from":0,"facets":{"popular_science":{"terms":{"field":"popular_science","size":1}},"isi":{"terms":{"field":"isi","size":1}},"type":{"terms":{"field":"type","size":25}},"status":{"terms":{"field":"status","size":8}},"year":{"terms":{"size":100,"field":"year","order":"reverse_term"}},"pmid":{"terms":{"field":"pmid","size":1}},"open_access":{"terms":{"size":1,"fields":["oa"]}},"extern":{"terms":{"size":2,"field":"extern"}}},"size":20,"sort":[{"date_updated":"desc"},{"year":"desc"}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.search.SearchParseException: [publication][4]: query[-status:deleted +ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [date_updated] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:140)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more
```

**Comment by phochste** [comment]
@lightonphiri The MariaDB error looks not good. Do you have some information which version of MariaDB and ElasticSearch you are running?

**Comment by nicolasfranck** [comment]
@lightonphiri the "id" of your publications, how to they look like?

**Comment by valid0r** [comment]
@lightonphiri MariaDB table charsets seem to default to `utf8mb4` (4 bytes per character) which seem to cause problems with the DBD::mysql package. Setting the db charsets to `utf8` in my.cnf seemed to solve the issue for us (running LibreCat on Ubuntu 18.04 LTS):
```
[client]
default-character-set=utf8
[mysql]
default-character-set=utf8
[mysqld]
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

Note that you have to either alter the existing tables or drop them and create new ones.

More info: https://mariadb.com/kb/en/library/setting-character-sets-and-collations/#example-changing-the-default-character-set-to-utf-8

**Comment by vpeil** [comment]
I close it now. Please, reopen if more things need to be discussed.
